### ISSUE TITLE
config 查询接口 lastModified 为 0

### ISSUE THREAD

**Issue by zhwaaaaaa** [nacos-group/r-nacos#107]
{\"resultCode\":200,\"errorCode\":0,\"message\":null,\"requestId\":null,\"content\":\"ccddccddccddffff\",\"encryptedDataKey\":null,\"contentType\":\"text\",\"md5\":\"ac4a3a3668a7660cf05dfcba26cdf7c9\",\"lastModified\":0,\"beta\":false,\"tag\":null}"

**Comment by zhwaaaaaa** [comment]
ConfigQueryResponse

**Comment by zhwaaaaaa** [comment]
跟 java 版本 返回 上次更新时间戳 毫秒

**Comment by zhwaaaaaa** [comment]
跟 java 版本 返回 上次更新时间戳 毫秒

**Comment by heqingpan** [comment]
收到，晚点确认一下。
如果确实有问题就当bug在后续版本优先修复。

**Comment by heqingpan** [comment]
> 我开发 打算 用 r-nacos 联调，结果以前已经测通 的功能 都跑不起来了[😂]

你用的是哪个版本的sdk?  测试的场景都有强依赖lastModified这个字段是吗？

**Comment by heqingpan** [comment]
r-nacos配置中心有用过多个语言sdk验证，常用的设置、查询、监听都有验证过。

之前的例子确定没有观注lastModified字段，不过不太至于所有功能都跑不起来吧😂？ 你测试例子都是依赖lastModified字段内容的吗？

**Comment by heqingpan** [comment]
老哥，我记起来了，你用的是你写的nginx扩展是吗？你之前有提过另一个issue，从你的角度来看确定不一致的点有点多😂


我手里没有你的环境，不然也可以考虑主动兼容。先优先适配社区的sdk。

**Comment by heqingpan** [comment]
刚好明天有个发布窗口，我争取明天发布的版本中修复这个问题。

**Comment by zhwaaaaaa** [comment]
> 刚好明天有个发布窗口，我争取明天发布的版本中修复这个问题。

感谢大佬，不管是 配置 监听 还是服务监听都引来 lastModified 字段，通过这个字段判断 服务 和配置是否发生了 编程，再 决定 是否更新到 共享内存

**Comment by heqingpan** [comment]
理解了。

上面的问题修复已经开发完成，确定可以和今天的版本一起发。
（大概会在今晚发布，明天可用。）

**Comment by heqingpan** [comment]
v0.5.13版本已解决
