### ISSUE TITLE
验证码校验失败

### ISSUE THREAD

**Issue by ZhangMingShuo** [nacos-group/r-nacos#109]
admin:admin登录控制台验证码校验失败

**Comment by ZhangMingShuo** [comment]
> admin:admin登录控制台验证码校验失败

qingpan/rnacos:latest镜像

**Comment by heqingpan** [comment]
环境、版本、日志信息可以提供一下。


这个问题有被咨询过几次，一般和数据无法写入文件有关。
可以确认一下是否有写入文件权限，可以看看nacos_db目录下的文件有没有内容。

**Comment by heqingpan** [comment]
![mmexport1719212861342](https://github.com/nacos-group/r-nacos/assets/1174480/9ba3059d-a71f-46d0-9701-8883e9e472f0)

部分docker 无写入权限可以在启动时加上上面的参数解决。

**Comment by ZhangMingShuo** [comment]
> 部分docker 无写入权限可以在启动时加上上面的参数解决。
### docker-compose.yml
 shanjupay-nacos:
    image: qingpan/rnacos:latest
    container_name: shanjupay-nacos
    privileged: true
    ports:
      - "8848:8848"
      - "9848:9848"
      - "10848:10848"
    volumes:
      - /var/nacos/io1:/io:rw
      - /etc/localtime:/etc/localtime:ro
    networks:
      - shanjupaynetwork
    environment:
      - RUST_LOG=warn
      - RNACOS_HTTP_PORT=8848
      - RNACOS_RAFT_NODE_ADDR=shanjupay-nacos:9848
      - RNACOS_CONFIG_DB_DIR=db
      - RNACOS_RAFT_NODE_ID=1
      - RNACOS_RAFT_AUTO_INIT=true
      - TZ=Asia/Shanghai
      - RNACOS_INIT_ADMIN_USERNAME=mingshuo
      - RNACOS_INIT_ADMIN_PASSWORD=mingshuo
    restart: always
    logging:
      #driver: none
      driver: json-file
      #options:
      #  max-size: 100m
  shanjupay-nacos-slave1: # 从节点
    image: qingpan/rnacos:latest
    container_name: shanjupay-nacos-slave1
    privileged: true
    environment: # 环境变量
      - RUST_LOG=warn
      - RNACOS_HTTP_PORT=8848
      - RNACOS_RAFT_NODE_ADDR=shanjupay-nacos-slave1:9848
      - RNACOS_CONFIG_DB_DIR=db
      - RNACOS_RAFT_NODE_ID=2
      - RNACOS_RAFT_JOIN_ADDR=shanjupay-nacos:9848
      - TZ=Asia/Shanghai
    volumes:
      - /var/nacos/io2:/io:rw
      - /etc/localtime:/etc/localtime:ro
    networks:
      - shanjupaynetwork
    restart: always
    depends_on:
      - shanjupay-nacos
    logging:
      #driver: none
      driver: json-file
  shanjupay-nacos-slave2: # 从节点
    image: qingpan/rnacos:latest
    container_name: shanjupay-nacos-slave2
    privileged: true
    environment: # 环境变量
      - RUST_LOG=warn
      - RNACOS_HTTP_PORT=8848
      - RNACOS_RAFT_NODE_ADDR=shanjupay-nacos-slave2:9848
      - RNACOS_CONFIG_DB_DIR=db
      - RNACOS_RAFT_NODE_ID=3
      - RNACOS_RAFT_JOIN_ADDR=shanjupay-nacos:9848
      - TZ=Asia/Shanghai
    volumes:
  - /var/nacos/io3:/io:rw
      - /etc/localtime:/etc/localtime:ro
    networks:
      - shanjupaynetwork
    restart: always
    depends_on:
      - shanjupay-nacos
      - shanjupay-nacos-slave1
    logging:
      #driver: none
      driver: json-file
### 日志
version:0.5.13, RUST_LOG:warn
data dir:db
rnacos started
[2024-06-24 15:19:02.061652 +08:00 ERROR async_raft_ext::core::vote] error while requesting vote from peer error=status: Unknown, message: "transport error: error trying to connect: dns error: failed to lookup address information: Name or service not known", details: [], metadata: MetadataMap { headers: {} } peer=2
[2024-06-24 15:19:02.061706 +08:00 ERROR async_raft_ext::core::vote] error while requesting vote from peer error=status: Unknown, message: "transport error: error trying to connect: dns error: failed to lookup address information: Name or service not known", details: [], metadata: MetadataMap { headers: {} } peer=3

**Comment by ZhangMingShuo** [comment]
> 环境、版本、日志信息可以提供一下。
> 
> 这个问题有被咨询过几次，一般和数据无法写入文件有关。 可以确认一下是否有写入文件权限，可以看看nacos_db目录下的文件有没有内容。

### 环境
Linux CentOS7.9 Tencent Cloud
docker 1.8

### 版本
version:0.5.13

### 日志
version:0.5.13, RUST_LOG:warn
data dir:db
rnacos started
[2024-06-24 15:19:02.061652 +08:00 ERROR async_raft_ext::core::vote] error while requesting vote from peer error=status: Unknown, message: "transport error: error trying to connect: dns error: failed to lookup address information: Name or service not known", details: [], metadata: MetadataMap { headers: {} } peer=2
[2024-06-24 15:19:02.061706 +08:00 ERROR async_raft_ext::core::vote] error while requesting vote from peer error=status: Unknown, message: "transport error: error trying to connect: dns error: failed to lookup address information: Name or service not known", details: [], metadata: MetadataMap { headers: {} } peer=3

### docker-compose.yml
 shanjupay-nacos:
    image: qingpan/rnacos:latest
    container_name: shanjupay-nacos
    privileged: true
    ports:
      - "8848:8848"
      - "9848:9848"
      - "10848:10848"
    volumes:
      - /var/nacos/io1:/io:rw
      - /etc/localtime:/etc/localtime:ro
    networks:
      - shanjupaynetwork
    environment:
      - RUST_LOG=warn
      - RNACOS_HTTP_PORT=8848
      - RNACOS_RAFT_NODE_ADDR=shanjupay-nacos:9848
      - RNACOS_CONFIG_DB_DIR=db
      - RNACOS_RAFT_NODE_ID=1
      - RNACOS_RAFT_AUTO_INIT=true
      - TZ=Asia/Shanghai
      - RNACOS_INIT_ADMIN_USERNAME=mingshuo
      - RNACOS_INIT_ADMIN_PASSWORD=mingshuo
    restart: always
    logging:
      #driver: none
      driver: json-file
      #options:
      #  max-size: 100m
  shanjupay-nacos-slave1: # 从节点
    image: qingpan/rnacos:latest
    container_name: shanjupay-nacos-slave1
    privileged: true
    environment: # 环境变量
      - RUST_LOG=warn
      - RNACOS_HTTP_PORT=8848
      - RNACOS_RAFT_NODE_ADDR=shanjupay-nacos-slave1:9848
      - RNACOS_CONFIG_DB_DIR=db
      - RNACOS_RAFT_NODE_ID=2
      - RNACOS_RAFT_JOIN_ADDR=shanjupay-nacos:9848
      - TZ=Asia/Shanghai
    volumes:
      - /var/nacos/io2:/io:rw
      - /etc/localtime:/etc/localtime:ro
    networks:
      - shanjupaynetwork
    restart: always
    depends_on:
      - shanjupay-nacos
    logging:
      #driver: none
      driver: json-file
  shanjupay-nacos-slave2: # 从节点
    image: qingpan/rnacos:latest
    container_name: shanjupay-nacos-slave2
    privileged: true
    environment: # 环境变量
      - RUST_LOG=warn
      - RNACOS_HTTP_PORT=8848
      - RNACOS_RAFT_NODE_ADDR=shanjupay-nacos-slave2:9848
      - RNACOS_CONFIG_DB_DIR=db
      - RNACOS_RAFT_NODE_ID=3
      - RNACOS_RAFT_JOIN_ADDR=shanjupay-nacos:9848
      - TZ=Asia/Shanghai
    volumes:
      - /var/nacos/io3:/io:rw
      - /etc/localtime:/etc/localtime:ro
    networks:
      - shanjupaynetwork
    restart: always
    depends_on:
      - shanjupay-nacos
      - shanjupay-nacos-slave1
    logging:
      #driver: none
      driver: json-file

**Comment by heqingpan** [comment]
你这个是集群部署场景。

看日志是域名解析有问题。

应该是你的配置有点问题

网络配置：networks:
- shanjupaynetwork
集群地址是：
RNACOS_RAFT_JOIN_ADDR=shanjupay-nacos:9848

这两个不一样。

**Comment by heqingpan** [comment]
docker-compose部署可以参考文档：

https://r-nacos.github.io/docs/notes/deploy_example/docker_cluster_deploy/
