### ISSUE TITLE
nacos-sdk-rust无法使用enable_auth_plugin_http进行账号密码登录

### ISSUE THREAD

**Issue by CoderXu** [nacos-group/r-nacos#110]
nacos-sdk-rust版本：0.4
r-nacos版本：0.5.12

![image](https://github.com/nacos-group/r-nacos/assets/9564977/9d186989-0300-4528-8513-329023664e6f)
登录会一直失败

nacos-sdk-rust 登录使用的是query
![image](https://github.com/nacos-group/r-nacos/assets/9564977/676648af-7617-4a50-9006-441abd4349e7)

实测r-nacos必须使用x-www-form-urlencoded方式登录可以成功
![image](https://github.com/nacos-group/r-nacos/assets/9564977/3b5eaf4e-f40c-47d0-9a5a-4ae93fc73f24)
![image](https://github.com/nacos-group/r-nacos/assets/9564977/0523a52e-bc23-4c48-ab6a-a7e5f6485937)

**Comment by heqingpan** [comment]
问题收到，下个版本支持。

（一般一周发布一次，发布窗口在周末）。

**Comment by heqingpan** [comment]
新发布的v0.5.14版本已处理。
