### ISSUE TITLE
r-nacos是个人项目么

### ISSUE THREAD

**Issue by cfdou** [nacos-group/r-nacos#116]
我是从博客园看到的这个项目，这两天安装试用了一下，感觉很不错，就是有点疑问，从issue的回答看这像是一个个人项目，但是它是在nacos-group下面，nacos本身是alibaba开源的，这个nacos-group属于啥组织呢，和alibaba有关系么

**Comment by heqingpan** [comment]
r-nacos最开始是个人项目，前不久仓库迁移到nacos-group社区，具体原由可参考 #66 。

nacos是alibaba下的一个开源项目。

nacos-group是nacos项目生态开源社区组织，组织本身主要由alibaba nacos开发组管理，其下的项目一般由社区人员开发、管理。

目前r-nacos是nacos-group下的一个项目，主要由我来管理。欢迎其它感兴趣的同学一起开发。

**Comment by cfdou** [comment]
> r-nacos最开始是个人项目，前不久仓库迁移到nacos-group社区，具体原由可参考 #66 。
> 
> nacos是alibaba下的一个开源项目。
> 
> nacos-group是nacos项目生态开源社区组织，组织本身主要由alibaba nacos开发组管理，其下的项目一般由社区人员开发、管理。
> 
> 目前r-nacos是nacos-group下的一个项目，主要由我来管理。欢迎其它感兴趣的同学一起开发共建。

感谢解答
