### ISSUE TITLE
0.5.17docker部署使用ip能正常访问，使用域名登录不上

### ISSUE THREAD

**Issue by falcon-jin** [nacos-group/r-nacos#119]
![image](https://github.com/user-attachments/assets/4021e8e7-9136-42c5-a31f-4de028d61baf)
![image](https://github.com/user-attachments/assets/637307c2-66cf-4fa9-84b0-5e2b8062f394)
deng'l登录成功 不会跳转界面

**Comment by heqingpan** [comment]
你使用什么路径登陆？
中国有经过nginx之类反向代理吗？

登陆后它不自动跳转，你试一下手动访问/rnacos/路径试试？

**Comment by falcon-jin** [comment]
version: '3'

#Networks(网络)
networks:
  ali: # 使用bridge驱动创建名为falcon的网络
    driver: bridge
# 先执行 docker-compose up -d nacos 启动nacos服务
# 等nacos启动成功之后 在执行 docker-compose up -d 命令启动其它服务 不然seata服务可能会启动报错
services:
  nacos:
    image: qingpan/rnacos:v0.5.17
    container_name: nacos
    restart: always
    environment:
      RNACOS_ENABLE_NO_AUTH_CONSOLE: false
      RNACOS_CONSOLE_ENABLE_CAPTCHA: false #验证码的开关
      RNACOS_HTTP_PORT: 8848 #r-nacos监听http端口
      RNACOS_GRPC_PORT: 9848 #r-nacos监听grpc端口
      RNACOS_HTTP_CONSOLE_PORT: 10848 #r-nacos独立控制台端口
      RNACOS_CONSOLE_LOGIN_ONE_HOUR_LIMIT: 5 #r-nacos控制台登录1小时失败次数限制 默认是5,一个用户连续登陆失败5次，会被锁定1个小时
      RNACOS_HTTP_WORKERS: 4 #http工作线程数 cpu核数
      RNACOS_CONFIG_DB_DIR: nacos_db #配置中心的本地数据库sled文件夹, 会在系统运行时自动创建
      RNACOS_RAFT_NODE_ID: 1 #节点id
      RUST_LOG: info #日志等级:debug,info,warn,error;所有http,grpc请求都会打info日志,如果不观注可以设置为error减少日志量
    ports:
      - "8848:8848"
      - "9848:9848"
      - "10848:10848"
    expose: [ "9848","8848" ]
    volumes:
      - ./nacos/nacos_db:/io/nacos_db
    privileged: true
    # network_mode: "host" #设置网络模式
    networks: # 使用创建的网络进行通信
      - ali
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

**Comment by falcon-jin** [comment]
![image](https://github.com/user-attachments/assets/76126b83-655c-4f59-a90a-e03959ae8fdb)

**Comment by falcon-jin** [comment]
没有经过nginx login接口登录成功 web_resurces接口返回未登录

**Comment by heqingpan** [comment]
可能和r-nacos没有写入文件权限有关，你确认一下对应目录有没有能产生数据。

**Comment by heqingpan** [comment]
如果nacos_db目前没有文件，那就是这个原因。

**Comment by falcon-jin** [comment]
我用ip可以正常访问 但是用域名访问就会出现上面的情况

**Comment by heqingpan** [comment]
> 我用ip可以正常访问 但是用域名访问就会出现上面的情况


那应该就和域名网络配置相关了。
你用的域名是怎么配置的？是不是有经过类似nginx的代理？

**Comment by falcon-jin** [comment]
> > 我用ip可以正常访问 但是用域名访问就会出现上面的情况
> 
> 那应该就和域名网络配置相关了。 你用的域名是怎么配置的？是不是有经过类似nginx的代理？

没有 就是阿里的二级域名解析 留着看别人会不会也有这问题吧
