### ISSUE TITLE
开源的前端代码是放在哪个目录啊

### ISSUE THREAD

**Issue by Xuzan9396** [nacos-group/r-nacos#135]

**Comment by Xuzan9396** [comment]
@heqingpan  好的谢谢，看到了引入了，楼主rust 代码写了多久了，最近也是在学rust

**Comment by heqingpan** [comment]
3年多一些吧。
刚学差不多就开始尝试写这个项目，中间有中段过些时间，一年多前才决定续写把它开源出来。
