### ISSUE TITLE
通过中间数据文件，支持数据备份、恢复、迁移

### ISSUE THREAD

**Issue by heqingpan** [nacos-group/r-nacos#138]
r-nacos运行时使用自定义的分布式文件存储，用户比较难以用程序或脚本记取、迁移、加工r-nacos中的数据。

为了支持用户更方便的管理、使用r-nacos中数据，计划通过语言无关的中间数据文件做数据载体，间接支持r-nacos系统数据和通用数据库数据双向迁移。

1. [x] 定义中间数据文件格式；
2. [x] 支持把r-nacos系统数据导出到中间数据文件；
3. [x] 支持把中间数据文件导入到r-nacos系统中；
4. [x] 支持把中间数据转化到sqlite数据库  （可能通过工具支持，待定）；
5. [x] 支持把约定的sqlite数据库表数据转化成中间数据文件（可能通过工具支持，待定）；
6. [x] 支持通过nacos open api接口把nacos数据(只含配置、命名空间数据)导出到中间数据文件，即r-nacos支持从nacos系统导入数据；
7. [x] 支持把nacos mysql数据（包含配置、命名空间、用户数据）导出为中间数据文件，即r-nacos支持从nacos 数据库导入数据（可能通过工具支持，待定）；

关联issue #89

**Comment by heqingpan** [comment]
r-nacos v0.6.0 版本已发布，r-nacos侧的数据备份、恢复、迁移功能已完成。

后续与外部数据转化功能待开发支持。

**Comment by cinling** [comment]
比较期待可以平滑从 nacos 转移到 rnacos 的功能

**Comment by heqingpan** [comment]
把nacos数据导出到r-nacos功能下周开始开发，快的话下周末完成，晚一些的话第二个周末应该也能完成。

**Comment by cinling** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
我也许不在，但我回尽快回复你的

**Comment by heqingpan** [comment]
v0.6.5版本已完成所有数据备份迁移相关的功能。
