### ISSUE TITLE
关键验证码不生效

### ISSUE THREAD

**Issue by PterX** [nacos-group/r-nacos#141]
RNACOS_CONSOLE_ENABLE_CAPTCHA 已经配置了false，还是出现验证码，而且还加载不出来，导致无法登录

**Comment by heqingpan** [comment]
> RNACOS_CONSOLE_ENABLE_CAPTCHA 已经配置了false，还是出现验证码，而且还加载不出来，导致无法登录

设置为false目前只是接口不校验验证码，前端目前还会出现验证码输入框，实际随便你输入后端是不校验的。

后面抽空让前端界面输入框显示和这个后端配置一起联动控制。

**Comment by PterX** [comment]
> > RNACOS_CONSOLE_ENABLE_CAPTCHA 已经配置了false，还是出现验证码，而且还加载不出来，导致无法登录
> 
> 设置为false目前只是接口不校验验证码，前端目前还会出现验证码输入框，实际随便你输入后端是不校验的。
> 
> 后面抽空让前端界面输入框显示和这个后端配置一起联动控制。

现在关闭验证码的情况系，登录会提示系统错误，看请求返回decode_password 错误

**Comment by heqingpan** [comment]
> 重新把容器删了再创建，验证码也能出来了，也登录进去了

这个之前倒是没有遇到过，不确定什么原因。

其它的问题基本都是前端没有适配关闭验证码相关的问题。

**Comment by heqingpan** [comment]
r-nacos v0.6.0版本中，关闭控制台验证码开关已支持前后端联动。

**Comment by PterX** [comment]
{
    "data": null,
    "success": false,
    "code": "SYSTEM_ERROR",
    "message": null
}
现在是真的登录不了了，删除docker 重新创建也还是一样

**Comment by heqingpan** [comment]
报错时服务端有什么错误日志吗？

这就有点奇怪，docker运行时主要和容器+数据有关，拷贝数据后能恢复可以认为是数据没有问题。
另一个面docker容器镜像，前后表现应该是一致的，你上面删除容器重新启动有换过容器镜像吗？对应的是什么版本？

**Comment by PterX** [comment]
> 报错时服务端有什么错误日志吗？
> 
> 这就有点奇怪，docker运行时主要和容器+数据有关，拷贝数据后能恢复可以认为是数据没有问题。 另一个面docker容器镜像，前后表现应该是一致的，你上面删除容器重新启动有换过容器镜像吗？对应的是什么版本？

服务端没有日志，日志过滤是warn。没有换过容器版本
