### ISSUE TITLE
k8s中部署

### ISSUE THREAD

**Issue by leyou240** [nacos-group/r-nacos#146]
请提供一下，在K8S环境下r-nacos的部署和使用相关demo。
因为在k8s外部署r-nacos，podip在外部无法访问

**Comment by heqingpan** [comment]
k8s环境可以使用[helm](https://github.com/nacos-group/r-nacos/tree/master/deploy/k8s/helm) 部署。

如果不想用helm,相使用statefulset yaml部署，可以参考 https://github.com/nacos-group/r-nacos/issues/140 这个issue中最后的成功部署样例。
