### ISSUE TITLE
编辑配置时查找替换光标无法定位到输入框

### ISSUE THREAD

**Issue by MrChenSH** [nacos-group/r-nacos#156]
![image](https://github.com/user-attachments/assets/03cd88e0-c0b5-4b48-9d32-ea4f50cf27d6)
想在编辑器内进行替换某个内容，结果光标一直定位到编辑器内部，无法在输入框输入想要替换的内容

还有就是能否对编辑器进行放大，现在的编辑体验有点差

**Comment by heqingpan** [comment]
问题已收到。

关于内容替换问题我晚点确认；关于编辑器支持放大后续有计划支持。

**Comment by MrChenSH** [comment]
> 问题都已确认，顺利的话本周未可以发一个版本解决这个问题。

好的，辛苦大佬

**Comment by heqingpan** [comment]
r-nacos v0.6.4新版本发布,此问题已解决。
