### ISSUE TITLE
请问服务探活接口可以用哪个？

### ISSUE THREAD

**Issue by CarlJia** [nacos-group/r-nacos#166]
用于检测 rnacos 服务是否正常

**Comment by heqingpan** [comment]
目前没有专门的接口用于健康检测，暂时可以用tcp端口探活。

后面考虑增加专门的接口用于检测服务是否正常运行。

**Comment by heqingpan** [comment]
快的话本周末，慢的话下周末可以发版支持。

**Comment by CarlJia** [comment]
> 目前没有专门的接口用于健康检测，暂时可以用tcp端口探活。
> 
> 后面考虑增加专门的接口用于检测服务是否正常运行。

感谢大佬解答，你把我一直想做的事（rust实现nacos）做掉了，很赞！

**Comment by heqingpan** [comment]
v0.6.6版本已支持，可以参考文档： https://r-nacos.github.io/docs/notes/health/

**Comment by CarlJia** [comment]
够高效的，赞
