### ISSUE TITLE
nacos不实时刷新配置内容

### ISSUE THREAD

**Issue by UFO233** [nacos-group/r-nacos#173]
<img width="961" alt="image" src="https://github.com/user-attachments/assets/6aeeb314-3251-4cb4-9dcc-dac5a289feb3">
<img width="1158" alt="image" src="https://github.com/user-attachments/assets/e81d5a39-9092-41ac-8101-62202588cf05">
<img width="814" alt="image" src="https://github.com/user-attachments/assets/a11bdfc5-cd1c-4c85-9161-9de53c5717df">

**Comment by heqingpan** [comment]
你的pom依赖和spring clond配置与启动应用的配置提供一下，才好判断。

一般可以从两方面排查：
1、确认使用的配置文件正确；
2、确认配置刷新对应的配置正确（可参考成功的项目配置）

本项目中的[样例](https://github.com/nacos-group/r-nacos/tree/master/sdk-examples/java/spring-cloud-v2)是支持配置刷新的，你也可以对比参考一下。

**Comment by heqingpan** [comment]
这种应该是应用配置的问题，如果不确定你也可以切换回java 版本nacos server对比看看结果是不是一致。

**Comment by UFO233** [comment]
> 这种应该是应用配置的问题，如果不确定你也可以切换回java 版本nacos server对比看看结果是不是一致。
搞定了，是我用法不当，感谢感谢
