### ISSUE TITLE
配置列表能否支持显示配置描述

### ISSUE THREAD

**Issue by Ai-Yolo** [nacos-group/r-nacos#179]
![image](https://github.com/user-attachments/assets/67b6b85a-3aff-4564-9fd8-f2cbefab21b8)
现在的列表留白太多，描述更适合在前台展示出来

**Comment by Ai-Yolo** [comment]
![image](https://github.com/user-attachments/assets/e23a750e-e8d6-48f4-a0e5-b93d9f4740fc)
服务实例列表有个错别字（健康状态

**Comment by heqingpan** [comment]
这个可以有，后面版本找机会加上。
错别字也会修改掉。

**Comment by heqingpan** [comment]
v0.6.7版本已支持
