### ISSUE TITLE
控制台用户管理中限制删除最后一个管理员，避免误操作。

### ISSUE THREAD

**Issue by heqingpan** [nacos-group/r-nacos#34]
控制台用户管理中限制删除最后一个管理员，避免误操作。

这是一个用户提的建议，建个 issue 记录下。

这个优化的优先级排在 raft 性能优化之后。

**Comment by a981008** [comment]
我尝试在删除时做限制，但角色信息是存储在 val 中的，好像没有什么高效的方式，只能挨个遍历。
如果以上方案可以的话，我可以提交这个 PR

**Comment by heqingpan** [comment]
先用遍历方案也可以，后面有必要再调整。

可以先判断当前删除的用户是否是管理员，如果是再遍历判断是否是唯一管理员。

**Comment by heqingpan** [comment]
已在r-nacos v0.6.1 版本处理。
