### ISSUE TITLE
面向SDK的接口增加鉴权

### ISSUE THREAD

**Issue by heqingpan** [nacos-group/r-nacos#65]
目前r-nacos是通过mock支持鉴权接口请求接口。所以鉴权流程能走通，但实际r-nacos内部不校验。

计划对openapi与grpc api增加鉴权。

1. 登陆获取token接口，校验用户密码通过后返回accessToken；1) accessToken可以像nacos一样放JWT信息 ; 2) accessToken也可以是缓存的key,校验时通过key取缓存中的值； 【r-nacos内部支持分布式缓存，目前用第2种缓存方案比较方便】
2. sdk调用r-nacos接口时,增加对token的有校性进行验证； 前期可以先只判断用户状态，不判断数据权限；后面管理后台支持配置用户数据权限后再加上数据权限校验；
3. r-nacos支持配置是否开启鉴权，默认不开启；

**Comment by moyu-x** [comment]
1. 目前觉得鉴权这个是强需求，在生产环境没有鉴权在安全性上比较受影响，并且应该默认开启鉴权。
2. 在安全测试是未授权访问是会被认为一个很严重的安全的问题，虽然在部署的时候会有防火墙，但是这个还是得需要的

**Comment by heqingpan** [comment]
之前确实是因为有内网防火墙所以把它的优先级放低。目前已经再排期，即将投入开发。

**Comment by FlowerBirds** [comment]
开发环境影响不大，如果要推广生产环境的话，鉴权是必须的。

持续关注！

**Comment by heqingpan** [comment]
上面列的内容开发，快的话本周末完成，大概可以在下周末发一个支持鉴权的版本。

**Comment by heqingpan** [comment]
【2024-05-11】

初步完成http openapi接口鉴权功能，并完成初步测试验证。
grpc接口鉴权待处理。

**Comment by heqingpan** [comment]
【2024-05-13】

初步完成grpc接口鉴权

**Comment by heqingpan** [comment]
发布的v0.5.8-beta.1版本已支持鉴权，观察一段时间没有问题后，再发布正式版本，预计在本周未。

**Comment by heqingpan** [comment]
v0.5.9版本已支持
