### ISSUE TITLE
修改配置 id 保存, 会生成多份配置

### ISSUE THREAD

**Issue by seth-shi** [nacos-group/r-nacos#72]
点击编辑配置(修改配置 id, 很危险, 可以弹窗提示), 然后提交会生成新的一份配置(猜测代码可能 create 和 update 没处理好)
建议把当前选择的命名空间保存到 localStorage, 不用每次都 public

**Comment by heqingpan** [comment]
关于修改配置id，系统底层是不支持直接修改配置id，只能通过创建新配置，再把旧配置删除。

目前的修改配置id本质上是为了方便复制配置或基于原配置设置新的配置。原配置是不会被删除的。应该没有危险性。

如果对用户造成了误解，后面可以考虑编辑时id不可变。不过这样做之后，应该需要再提供一个口子方便配置复制。

关于命名空间在浏览器的持久化，这是一个不错的建议，当做一个future后面支持。

**Comment by seth-shi** [comment]
确实不应该修改 id, 复制内容到一个创建配置的页面, 这个可行

**Comment by heqingpan** [comment]
> 确实不应该修改 id, 复制内容到一个创建配置的页面, 这个可行

基本认同你的建议，之后会按这个方案来调整。

控制台的优化优先级会排在接口鉴权之后。估计还需要一段时间。

**Comment by seth-shi** [comment]
辛苦了, 感谢你的这个配置中心, 我这边测试环境跑一段时间看看
