### ISSUE TITLE
缺失能力：基于命名空间切换配置列表

### ISSUE THREAD

**Issue by fightingbamboo** [nacos-group/r-nacos#74]
<img width="1384" alt="image" src="https://github.com/nacos-group/r-nacos/assets/1464446/f3f0af77-9f16-47a4-81ce-9cd7a889db7a">
如图

**Comment by heqingpan** [comment]
这个功能是有的，切换命名空间是在列表页右上角的下拉框组件。

**Comment by fightingbamboo** [comment]
> 这个功能是有的，r-nacos切换命名空间是在列表页右上角的下拉框组件。

抱歉！我刚去看了下，确实是有

**Comment by fightingbamboo** [comment]
批量导入配置可以支持下吗？我们项目微服务数量比较多，配置一个一个导入效率太低了

**Comment by heqingpan** [comment]
> 批量导入配置可以支持下吗？我们项目微服务数量比较多，配置一个一个导入效率太低了

支持批量导入从nacos导出的配置。
一次只支持导入同一个命名空间的所有配置，多个命名空间的配置要分多次导入。

**Comment by heqingpan** [comment]
> > 这个功能是有的，r-nacos切换命名空间是在列表页右上角的下拉框组件。
> 
> 抱歉！我刚去看了下，确实是有

没关系，这也算是用户第一资使用反应的反馈。

可能在交互上对新用户没有足够的提示，后面可以考虑在下拉框边上加上"命名空间"文字用于提示。
