### ISSUE TITLE
两天用下来提几个建议

### ISSUE THREAD

**Issue by seth-shi** [nacos-group/r-nacos#75]
1. 登录 v2 有人反馈可以关闭验证码(增加个回车登录, 还要点一次鼠标)
2. 可以加一个 yaml, json 等校验的库, 现在 json 错了没提示

**Comment by heqingpan** [comment]
第1点，后面计划支持通过配置控制是否禁用验证码（关闭后，安全性会下降一些）

第2点，后面计划增强yaml,json等格式的校验提示。

目前我们正在对控制台页面重构，上面两点都要等重构完成之后再开发支持，估计还需要一小段时间。

**Comment by seth-shi** [comment]
> 第1点，后面计划支持通过配置控制是否禁用验证码（关闭后，安全性会下降一些）
> 
> 第2点，后面计划增强yaml,json等格式的校验提示。
> 
> 目前我们正在对控制台页面重构，上面两点都要等重构完成之后再开发支持，估计还需要一小段时间。

我在自己的电脑用 curl http 端口, 发现提示 config data don't exists. 这个能提示具体一点吗? 或者怎么开 debug 之类的模式提示. 我确认我的参数没问题

**Comment by heqingpan** [comment]
这个提示就是找不到配置。
配置key是由命名空间空间、分组、配置id决定的。
你可以再确认一下，或者把控制台的内容与curl命令发出来我们一起确认一下。

**Comment by seth-shi** [comment]
> 这个提示就是找不到配置。 配置key是由命名空间空间、分组、配置id决定的。 你可以再确认一下，或者把控制台的内容与curl命令发出来我们一起确认一下。

我现在没在那台电脑, 我的本意是提示一下用户具体是那个 group, id, namespace. 我之前没加引号会让后端没获取到准确的参数, 或者参数值包含特殊字符等等, 把实际后端获取到的输出一下
