### ISSUE TITLE
强烈建议把控制台配置编辑器换成MonacoEditor这个CodeMirror实在是一言难尽

### ISSUE THREAD

**Issue by zhaobingss** [nacos-group/r-nacos#80]
没找到控制台UI的在哪个目录下，迫切的想改掉这个编辑器

**Comment by heqingpan** [comment]
前端工程是分开的，在readme最后部分有说明。

https://github.com/r-nacos/rnacos-console-web

换成Monaco这个打包出来的文件会不会大比较多？

**Comment by heqingpan** [comment]
欢迎提pr😀

**Comment by zhaobingss** [comment]
@heqingpan 确实，我换成Monaco后打包后的文件多3.8M，还是单个文件，看来这个PR还是别提了，这个Monaco看来还是不太适合web😅

**Comment by heqingpan** [comment]
是的，当时没选强大的Monaco就是因为它太大了😂
