### ISSUE TITLE
界面404

### ISSUE THREAD

**Issue by 1321731966** [nacos-group/r-nacos#81]
大佬，http://127.0.0.1:10848/rnacos/ 这个路径UI界面访问为啥404啊

我用的浏览器是Chrome117.0.5938.63

**Comment by 1321731966** [comment]
从0.5.7换到0.5.6就好了

**Comment by heqingpan** [comment]
有点奇怪，我这边没能复现。

方便提供一下出问题时在浏览器中的请求与响应的信息吗？

**Comment by 1321731966** [comment]
浏览器没啥响应，因为是内网不方便给您截图，我大概描述一下,就是访问http://ip:10848/rnacos/ 这个路径时,会返会一个404的界面，应该就是r-nacos的404界面，然后上面地址变成了 http://ip:10848/rnacos/404?regirect_url =/ 看着像是所有请求都被重定向到了404

**Comment by heqingpan** [comment]
我用chrome和firefox的隐私模式暂时都没能复现。

有可能有浏览器相关，后面想办法试试切换成Chrome117再试试。（0.5.7不行0.5.6可以，也可能是其它原因）

想确认下：
+ 当时请求的地址是直接访问，还是经过nginx之类转发过？
+ 当时运行的服务端是什么系统？

**Comment by 1321731966** [comment]
直接在浏览器上访问的地址，服务端是centos，我回家自己又试了一下，是没问题的，可能是公司的服务器有问题，麻烦你了

**Comment by heqingpan** [comment]
我今天测试上周末发布的beta版本[v0.5.8-beta.1](https://github.com/nacos-group/r-nacos/releases/tag/v0.5.8-beta.1) 能复现你上面描述的现象。
beta版本中控制台前端使用的是最近大重构后版本，这部分还有点问题。

如果前两天用docker部署 qingpan/rnacos:latest 对应的是v0.5.8-beta.1就会有问题，如果用qingpan/rnacos:stable则对应的是最后正式版本v0.5.7应该没有问题。

确认下上面你说有问题的版本是v0.5.7，这个版本号你是如何判断的？ 

如果是非docker部署，可以用`rnacos --version`确认版本号，运行日志应该也会有版本号信息。

**Comment by 1321731966** [comment]
对不起,是我下载错了,我用你说的查看版本号的方式看了的确是beta版本,压缩包长得都一样哈，建议安装包的命名加上版本号

**Comment by heqingpan** [comment]
了解，那就是已确认原因，这个问题最新版本已解决。

关于文件名加版本号，因目前的文件名已经比较长，暂不考虑加。
