### ISSUE TITLE
go的客户端SDK注册json配置项界面显示的配置类型为text

### ISSUE THREAD

**Issue by 1321731966** [nacos-group/r-nacos#87]
go的客户端SDK注册json配置项界面显示的配置类型为text
client,PublishConfig(vo.ConfigParam{
   Content:"{}"，
   Group:"xxxxx",
   DataId:"xxxxx",
   Type:"json",
})
同样的客户端SDK代码在java版的nacos上界面显示的格式正确

**Comment by heqingpan** [comment]
新版本v0.5.11已支持此功能
