### ISSUE TITLE
重启可能会导致数据丢失假象

### ISSUE THREAD

**Issue by Clownsw** [nacos-group/r-nacos#88]
反复重启(停止 -> 开启) `r-nacos`, 配置、用户全部丢失假象(回到默认状态), 非连续性触发了十次有个五六次 (windows)
r-nacos: `0.5.7` (配置文件默认)

**Comment by heqingpan** [comment]
如果方便的话，可以按你在windows重启的方式在linux服务测试一般看看，两个系统的表现是不是一致？

**Comment by heqingpan** [comment]
收到，看来我得先到windows系统尝试复现确认问题。

**Comment by heqingpan** [comment]
此问题已复现并在v0.5.15解决。

其原因是：在windows环境下关闭进程后快速打开，第二次启动时可能因为第一资关闭的文件没有完全释放，导致第二次进程没能加载历史数据（数据列表为空白）；重启后可以数据能重新加载恢复。

解决方案：主动引入文件锁(一个放到nacos_db目录的空文件)；进程启动时先获取文件锁，如果获取不到则直接报错退出；应用应用退出时自动释放文件锁。

引入文件机制锁后，按之前的方式操作没有再出现这个现象，就当做这个问题已处理。
