### ISSUE TITLE
历史记录拿到的都是当前的值

### ISSUE THREAD

**Issue by yuqiyi** [nacos-group/r-nacos#95]
历史记录里面进行比对，比对的两个文件都是当前值，并非真实的历史记录。
并且恢复完成之后，之前设置的配置格式也没有了。
这个不好放图，自己修改下然后点下详情和恢复就看到了。
版本是v0.5.9。

**Comment by yuqiyi** [comment]
不是这个意思，是说历史记录，无论看哪一条记录，看到的都是当前值，并且点击恢复，恢复的两边对比，两边都是当前值，也就是说恢复没有用，点击确定的话，恢复的也还是当前值。

**Comment by heqingpan** [comment]
那可能是最版本控制台引入的，我周末确认一下。

你可以先用v0.5.7版本，这个是重构前的控制台，应该没有这个问题。
